//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace Web.nsysusso {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DemoBinding", Namespace="http://ssotemp1.nsysu.edu.tw/ssoWebservice")]
    public partial class get_user_info : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authUser3OperationCompleted;
        
        private System.Threading.SendOrPostCallback authUser2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getAttr2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getAttr3OperationCompleted;
        
        private System.Threading.SendOrPostCallback verifySessionIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyStuSessionIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifySessionIdReturnAttrOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyStuSessionIdReturnAttrOperationCompleted;
        
        private System.Threading.SendOrPostCallback userinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback authUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAttrOperationCompleted;
        
        private System.Threading.SendOrPostCallback authStuOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStuAttrOperationCompleted;
        
        private System.Threading.SendOrPostCallback authStuOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStuOutAttrOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifypwdexpiredOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public get_user_info() {
            this.Url = global::Web.Properties.Settings.Default.Web_nsysusso_get_user_info;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authUser3CompletedEventHandler authUser3Completed;
        
        /// <remarks/>
        public event authUser2CompletedEventHandler authUser2Completed;
        
        /// <remarks/>
        public event getAttr2CompletedEventHandler getAttr2Completed;
        
        /// <remarks/>
        public event getAttr3CompletedEventHandler getAttr3Completed;
        
        /// <remarks/>
        public event verifySessionIdCompletedEventHandler verifySessionIdCompleted;
        
        /// <remarks/>
        public event verifyStuSessionIdCompletedEventHandler verifyStuSessionIdCompleted;
        
        /// <remarks/>
        public event verifySessionIdReturnAttrCompletedEventHandler verifySessionIdReturnAttrCompleted;
        
        /// <remarks/>
        public event verifyStuSessionIdReturnAttrCompletedEventHandler verifyStuSessionIdReturnAttrCompleted;
        
        /// <remarks/>
        public event userinfoCompletedEventHandler userinfoCompleted;
        
        /// <remarks/>
        public event getUserInfoCompletedEventHandler getUserInfoCompleted;
        
        /// <remarks/>
        public event authUserCompletedEventHandler authUserCompleted;
        
        /// <remarks/>
        public event getAttrCompletedEventHandler getAttrCompleted;
        
        /// <remarks/>
        public event authStuCompletedEventHandler authStuCompleted;
        
        /// <remarks/>
        public event getStuAttrCompletedEventHandler getStuAttrCompleted;
        
        /// <remarks/>
        public event authStuOutCompletedEventHandler authStuOutCompleted;
        
        /// <remarks/>
        public event getStuOutAttrCompletedEventHandler getStuOutAttrCompleted;
        
        /// <remarks/>
        public event verifypwdexpiredCompletedEventHandler verifypwdexpiredCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#authUser3", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string authUser3(string param1, string param2, string param3, string param4) {
            object[] results = this.Invoke("authUser3", new object[] {
                        param1,
                        param2,
                        param3,
                        param4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authUser3Async(string param1, string param2, string param3, string param4) {
            this.authUser3Async(param1, param2, param3, param4, null);
        }
        
        /// <remarks/>
        public void authUser3Async(string param1, string param2, string param3, string param4, object userState) {
            if ((this.authUser3OperationCompleted == null)) {
                this.authUser3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthUser3OperationCompleted);
            }
            this.InvokeAsync("authUser3", new object[] {
                        param1,
                        param2,
                        param3,
                        param4}, this.authUser3OperationCompleted, userState);
        }
        
        private void OnauthUser3OperationCompleted(object arg) {
            if ((this.authUser3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authUser3Completed(this, new authUser3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#authUser2", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string authUser2(string param1, string param2, string param3, string param4) {
            object[] results = this.Invoke("authUser2", new object[] {
                        param1,
                        param2,
                        param3,
                        param4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authUser2Async(string param1, string param2, string param3, string param4) {
            this.authUser2Async(param1, param2, param3, param4, null);
        }
        
        /// <remarks/>
        public void authUser2Async(string param1, string param2, string param3, string param4, object userState) {
            if ((this.authUser2OperationCompleted == null)) {
                this.authUser2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthUser2OperationCompleted);
            }
            this.InvokeAsync("authUser2", new object[] {
                        param1,
                        param2,
                        param3,
                        param4}, this.authUser2OperationCompleted, userState);
        }
        
        private void OnauthUser2OperationCompleted(object arg) {
            if ((this.authUser2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authUser2Completed(this, new authUser2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getAttr2", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getAttr2(string param1, string param2, string param3, string param4, string param5) {
            object[] results = this.Invoke("getAttr2", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAttr2Async(string param1, string param2, string param3, string param4, string param5) {
            this.getAttr2Async(param1, param2, param3, param4, param5, null);
        }
        
        /// <remarks/>
        public void getAttr2Async(string param1, string param2, string param3, string param4, string param5, object userState) {
            if ((this.getAttr2OperationCompleted == null)) {
                this.getAttr2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAttr2OperationCompleted);
            }
            this.InvokeAsync("getAttr2", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5}, this.getAttr2OperationCompleted, userState);
        }
        
        private void OngetAttr2OperationCompleted(object arg) {
            if ((this.getAttr2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAttr2Completed(this, new getAttr2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getAttr3", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getAttr3(string param1, string param2, string param3, string param4, string param5) {
            object[] results = this.Invoke("getAttr3", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAttr3Async(string param1, string param2, string param3, string param4, string param5) {
            this.getAttr3Async(param1, param2, param3, param4, param5, null);
        }
        
        /// <remarks/>
        public void getAttr3Async(string param1, string param2, string param3, string param4, string param5, object userState) {
            if ((this.getAttr3OperationCompleted == null)) {
                this.getAttr3OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAttr3OperationCompleted);
            }
            this.InvokeAsync("getAttr3", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5}, this.getAttr3OperationCompleted, userState);
        }
        
        private void OngetAttr3OperationCompleted(object arg) {
            if ((this.getAttr3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAttr3Completed(this, new getAttr3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#verifySessionId", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string verifySessionId(string param1) {
            object[] results = this.Invoke("verifySessionId", new object[] {
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifySessionIdAsync(string param1) {
            this.verifySessionIdAsync(param1, null);
        }
        
        /// <remarks/>
        public void verifySessionIdAsync(string param1, object userState) {
            if ((this.verifySessionIdOperationCompleted == null)) {
                this.verifySessionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifySessionIdOperationCompleted);
            }
            this.InvokeAsync("verifySessionId", new object[] {
                        param1}, this.verifySessionIdOperationCompleted, userState);
        }
        
        private void OnverifySessionIdOperationCompleted(object arg) {
            if ((this.verifySessionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifySessionIdCompleted(this, new verifySessionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#verifyStuSessionId", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string verifyStuSessionId(string param1) {
            object[] results = this.Invoke("verifyStuSessionId", new object[] {
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifyStuSessionIdAsync(string param1) {
            this.verifyStuSessionIdAsync(param1, null);
        }
        
        /// <remarks/>
        public void verifyStuSessionIdAsync(string param1, object userState) {
            if ((this.verifyStuSessionIdOperationCompleted == null)) {
                this.verifyStuSessionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyStuSessionIdOperationCompleted);
            }
            this.InvokeAsync("verifyStuSessionId", new object[] {
                        param1}, this.verifyStuSessionIdOperationCompleted, userState);
        }
        
        private void OnverifyStuSessionIdOperationCompleted(object arg) {
            if ((this.verifyStuSessionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyStuSessionIdCompleted(this, new verifyStuSessionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#verifySessionIdReturnAttr", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string verifySessionIdReturnAttr(string param1, string param2) {
            object[] results = this.Invoke("verifySessionIdReturnAttr", new object[] {
                        param1,
                        param2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifySessionIdReturnAttrAsync(string param1, string param2) {
            this.verifySessionIdReturnAttrAsync(param1, param2, null);
        }
        
        /// <remarks/>
        public void verifySessionIdReturnAttrAsync(string param1, string param2, object userState) {
            if ((this.verifySessionIdReturnAttrOperationCompleted == null)) {
                this.verifySessionIdReturnAttrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifySessionIdReturnAttrOperationCompleted);
            }
            this.InvokeAsync("verifySessionIdReturnAttr", new object[] {
                        param1,
                        param2}, this.verifySessionIdReturnAttrOperationCompleted, userState);
        }
        
        private void OnverifySessionIdReturnAttrOperationCompleted(object arg) {
            if ((this.verifySessionIdReturnAttrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifySessionIdReturnAttrCompleted(this, new verifySessionIdReturnAttrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#verifyStuSessionIdReturnAttr", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string verifyStuSessionIdReturnAttr(string param1, string param2) {
            object[] results = this.Invoke("verifyStuSessionIdReturnAttr", new object[] {
                        param1,
                        param2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifyStuSessionIdReturnAttrAsync(string param1, string param2) {
            this.verifyStuSessionIdReturnAttrAsync(param1, param2, null);
        }
        
        /// <remarks/>
        public void verifyStuSessionIdReturnAttrAsync(string param1, string param2, object userState) {
            if ((this.verifyStuSessionIdReturnAttrOperationCompleted == null)) {
                this.verifyStuSessionIdReturnAttrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyStuSessionIdReturnAttrOperationCompleted);
            }
            this.InvokeAsync("verifyStuSessionIdReturnAttr", new object[] {
                        param1,
                        param2}, this.verifyStuSessionIdReturnAttrOperationCompleted, userState);
        }
        
        private void OnverifyStuSessionIdReturnAttrOperationCompleted(object arg) {
            if ((this.verifyStuSessionIdReturnAttrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyStuSessionIdReturnAttrCompleted(this, new verifyStuSessionIdReturnAttrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#userinfo", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string userinfo(string param1) {
            object[] results = this.Invoke("userinfo", new object[] {
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void userinfoAsync(string param1) {
            this.userinfoAsync(param1, null);
        }
        
        /// <remarks/>
        public void userinfoAsync(string param1, object userState) {
            if ((this.userinfoOperationCompleted == null)) {
                this.userinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserinfoOperationCompleted);
            }
            this.InvokeAsync("userinfo", new object[] {
                        param1}, this.userinfoOperationCompleted, userState);
        }
        
        private void OnuserinfoOperationCompleted(object arg) {
            if ((this.userinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userinfoCompleted(this, new userinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getUserInfo", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getUserInfo(string param1) {
            object[] results = this.Invoke("getUserInfo", new object[] {
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserInfoAsync(string param1) {
            this.getUserInfoAsync(param1, null);
        }
        
        /// <remarks/>
        public void getUserInfoAsync(string param1, object userState) {
            if ((this.getUserInfoOperationCompleted == null)) {
                this.getUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserInfoOperationCompleted);
            }
            this.InvokeAsync("getUserInfo", new object[] {
                        param1}, this.getUserInfoOperationCompleted, userState);
        }
        
        private void OngetUserInfoOperationCompleted(object arg) {
            if ((this.getUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserInfoCompleted(this, new getUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#authUser", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string authUser(string param1, string param2, string param3) {
            object[] results = this.Invoke("authUser", new object[] {
                        param1,
                        param2,
                        param3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authUserAsync(string param1, string param2, string param3) {
            this.authUserAsync(param1, param2, param3, null);
        }
        
        /// <remarks/>
        public void authUserAsync(string param1, string param2, string param3, object userState) {
            if ((this.authUserOperationCompleted == null)) {
                this.authUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthUserOperationCompleted);
            }
            this.InvokeAsync("authUser", new object[] {
                        param1,
                        param2,
                        param3}, this.authUserOperationCompleted, userState);
        }
        
        private void OnauthUserOperationCompleted(object arg) {
            if ((this.authUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authUserCompleted(this, new authUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getAttr", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getAttr(string param1, string param2, string param3, string param4) {
            object[] results = this.Invoke("getAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAttrAsync(string param1, string param2, string param3, string param4) {
            this.getAttrAsync(param1, param2, param3, param4, null);
        }
        
        /// <remarks/>
        public void getAttrAsync(string param1, string param2, string param3, string param4, object userState) {
            if ((this.getAttrOperationCompleted == null)) {
                this.getAttrOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAttrOperationCompleted);
            }
            this.InvokeAsync("getAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4}, this.getAttrOperationCompleted, userState);
        }
        
        private void OngetAttrOperationCompleted(object arg) {
            if ((this.getAttrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAttrCompleted(this, new getAttrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#authStu", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string authStu(string param1, string param2, string param3, string param4) {
            object[] results = this.Invoke("authStu", new object[] {
                        param1,
                        param2,
                        param3,
                        param4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authStuAsync(string param1, string param2, string param3, string param4) {
            this.authStuAsync(param1, param2, param3, param4, null);
        }
        
        /// <remarks/>
        public void authStuAsync(string param1, string param2, string param3, string param4, object userState) {
            if ((this.authStuOperationCompleted == null)) {
                this.authStuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthStuOperationCompleted);
            }
            this.InvokeAsync("authStu", new object[] {
                        param1,
                        param2,
                        param3,
                        param4}, this.authStuOperationCompleted, userState);
        }
        
        private void OnauthStuOperationCompleted(object arg) {
            if ((this.authStuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authStuCompleted(this, new authStuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getStuAttr", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getStuAttr(string param1, string param2, string param3, string param4, string param5) {
            object[] results = this.Invoke("getStuAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStuAttrAsync(string param1, string param2, string param3, string param4, string param5) {
            this.getStuAttrAsync(param1, param2, param3, param4, param5, null);
        }
        
        /// <remarks/>
        public void getStuAttrAsync(string param1, string param2, string param3, string param4, string param5, object userState) {
            if ((this.getStuAttrOperationCompleted == null)) {
                this.getStuAttrOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStuAttrOperationCompleted);
            }
            this.InvokeAsync("getStuAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5}, this.getStuAttrOperationCompleted, userState);
        }
        
        private void OngetStuAttrOperationCompleted(object arg) {
            if ((this.getStuAttrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStuAttrCompleted(this, new getStuAttrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#authStuOut", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string authStuOut(string param1, string param2, string param3, string param4) {
            object[] results = this.Invoke("authStuOut", new object[] {
                        param1,
                        param2,
                        param3,
                        param4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authStuOutAsync(string param1, string param2, string param3, string param4) {
            this.authStuOutAsync(param1, param2, param3, param4, null);
        }
        
        /// <remarks/>
        public void authStuOutAsync(string param1, string param2, string param3, string param4, object userState) {
            if ((this.authStuOutOperationCompleted == null)) {
                this.authStuOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthStuOutOperationCompleted);
            }
            this.InvokeAsync("authStuOut", new object[] {
                        param1,
                        param2,
                        param3,
                        param4}, this.authStuOutOperationCompleted, userState);
        }
        
        private void OnauthStuOutOperationCompleted(object arg) {
            if ((this.authStuOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authStuOutCompleted(this, new authStuOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#getStuOutAttr", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getStuOutAttr(string param1, string param2, string param3, string param4, string param5) {
            object[] results = this.Invoke("getStuOutAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStuOutAttrAsync(string param1, string param2, string param3, string param4, string param5) {
            this.getStuOutAttrAsync(param1, param2, param3, param4, param5, null);
        }
        
        /// <remarks/>
        public void getStuOutAttrAsync(string param1, string param2, string param3, string param4, string param5, object userState) {
            if ((this.getStuOutAttrOperationCompleted == null)) {
                this.getStuOutAttrOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStuOutAttrOperationCompleted);
            }
            this.InvokeAsync("getStuOutAttr", new object[] {
                        param1,
                        param2,
                        param3,
                        param4,
                        param5}, this.getStuOutAttrOperationCompleted, userState);
        }
        
        private void OngetStuOutAttrOperationCompleted(object arg) {
            if ((this.getStuOutAttrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStuOutAttrCompleted(this, new getStuOutAttrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-demo#verifypwdexpired", RequestNamespace="urn:xmethods-delayed-demo", ResponseNamespace="urn:xmethods-delayed-demo")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string verifypwdexpired(string param1) {
            object[] results = this.Invoke("verifypwdexpired", new object[] {
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifypwdexpiredAsync(string param1) {
            this.verifypwdexpiredAsync(param1, null);
        }
        
        /// <remarks/>
        public void verifypwdexpiredAsync(string param1, object userState) {
            if ((this.verifypwdexpiredOperationCompleted == null)) {
                this.verifypwdexpiredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifypwdexpiredOperationCompleted);
            }
            this.InvokeAsync("verifypwdexpired", new object[] {
                        param1}, this.verifypwdexpiredOperationCompleted, userState);
        }
        
        private void OnverifypwdexpiredOperationCompleted(object arg) {
            if ((this.verifypwdexpiredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifypwdexpiredCompleted(this, new verifypwdexpiredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void authUser3CompletedEventHandler(object sender, authUser3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authUser3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authUser3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void authUser2CompletedEventHandler(object sender, authUser2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authUser2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authUser2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getAttr2CompletedEventHandler(object sender, getAttr2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAttr2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAttr2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getAttr3CompletedEventHandler(object sender, getAttr3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAttr3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAttr3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verifySessionIdCompletedEventHandler(object sender, verifySessionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifySessionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifySessionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verifyStuSessionIdCompletedEventHandler(object sender, verifyStuSessionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyStuSessionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyStuSessionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verifySessionIdReturnAttrCompletedEventHandler(object sender, verifySessionIdReturnAttrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifySessionIdReturnAttrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifySessionIdReturnAttrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verifyStuSessionIdReturnAttrCompletedEventHandler(object sender, verifyStuSessionIdReturnAttrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyStuSessionIdReturnAttrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyStuSessionIdReturnAttrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void userinfoCompletedEventHandler(object sender, userinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getUserInfoCompletedEventHandler(object sender, getUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void authUserCompletedEventHandler(object sender, authUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getAttrCompletedEventHandler(object sender, getAttrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAttrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAttrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void authStuCompletedEventHandler(object sender, authStuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authStuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authStuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getStuAttrCompletedEventHandler(object sender, getStuAttrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStuAttrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStuAttrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void authStuOutCompletedEventHandler(object sender, authStuOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authStuOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authStuOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getStuOutAttrCompletedEventHandler(object sender, getStuOutAttrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStuOutAttrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStuOutAttrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verifypwdexpiredCompletedEventHandler(object sender, verifypwdexpiredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifypwdexpiredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifypwdexpiredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591